server:
  port: 8040
  #(改)应用上下文，统一用/jinbiao-user
  servlet:
    context-path: /jinbiao-user

spring:
  application:
    name: jinbiao-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: jinbiao-namespace
        #cluster-name: BJ
        #group: tulingshop
        ephemeral: false     #永久实例
  #数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/xiaofa_lawyer?connectTimeout=1000000&socketTimeout=3000000&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'


