server:
  port: 8040
  #(改)应用上下文，统一用/jinbiao-user
  servlet:
    context-path: /jinbiao-user

spring:
  application:
    name: jinbiao-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: jinbiao-namespace
#        cluster-name: SH
        #group: tulingshop
#        ephemeral: false     #永久实例

#    RestTemplate整合LoadBalancer可以替代ribbon
#    loadbalancer:
#      ribbon:
#        enabled: false

  #数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/xiaofa_lawyer?connectTimeout=1000000&socketTimeout=3000000&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

ribbon:
  eager-load:
    enabled: true
    clients: jinbiao-order

management:
  endpoints:
    web:
      exposure:
        include: '*'

#在yml配置文件中配置 Client 的日志级别才能正常输出日志，格式是"logging.level.feign接口包路径=debug"
logging:
  level:
    com.tuling.mall.user.rpc: debug

feign:
  #feign 使用 okhttp
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
#  client:
#    config:
#      jinbiao-order:   #对应微服务
#        loggerLevel: BASIC
#        requestInterceptors[0]:  #配置拦截器
#          com.tuling.mall.user.config.FeignAuthRequestInterceptor
        # 连接超时时间，默认2s
#        connectTimeout: 2000
#        # 请求处理超时时间，默认5s
#        readTimeout: 4000
  # 配置 GZIP 来压缩数据
  compression:
    request:
      enabled: true
      # 配置压缩的类型
      mime-types: text/xml,application/xml,application/json
      # 最小压缩值
      min-request-size: 2048
    response:
      enabled: true



