server:
  port: 8040
  #(改)应用上下文，统一用/jinbiao-user
  servlet:
    context-path: /jinbiao-user

spring:
  application:
    name: jinbiao-user  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        namespace: jinbiao-namespace
#        cluster-name: SH
        #group: tulingshop
#        ephemeral: false     #永久实例

#    RestTemplate整合LoadBalancer可以替代ribbon
#    loadbalancer:
#      ribbon:
#        enabled: false

    #使用sentinel限流、熔断规则
    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: 127.0.0.1:8080
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        port: 8719
      # 将其配置为 false 即可根据不同的 URL 进行链路限流
      web-context-unify: false

  #数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/seata_at_account?connectTimeout=1000000&socketTimeout=3000000&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/seata_at_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.powersi.entity
  #设置sql打印
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #设置驼峰命名法
    map-underscore-to-camel-case: true


ribbon:
  eager-load:
    enabled: true
    clients: jinbiao-order

#暴露actuator端点,添加Sentinel后，需要暴露/actuator/sentinel端点,而Springboot默认是没有暴露该端点的，所以需要设置
management:
  endpoints:
    web:
      exposure:
        include: '*'

#在yml配置文件中配置 Client 的日志级别才能正常输出日志，格式是"logging.level.feign接口包路径=debug"
logging:
  level:
    com.tuling.mall.user.rpc: debug
    com: debug

feign:
# 配置 Feign 远程调用
  circuitbreaker:
    enable: true
  hystrix:
    # 为 Feign 开启 Hystrix熔断机制，就可以使用回调
    enabled: true
  #feign 使用 okhttp不需要再指定gzip压缩，使用httpclient需要指定下使用gzip压缩数据传输，提升传输性能,rpc日志： Accept-Encoding: gzip
  httpclient:
    enabled: true
#  okhttp:
#    enabled: true
  client:
    config:
      jinbiao-order:   #对应微服务
        loggerLevel: FULL
        #配置拦截器
        requestInterceptors[0]: com.tuling.mall.user.config.FeignAuthRequestInterceptor
#         连接超时时间，默认2s
        connectTimeout: 2000
        # 请求处理超时时间，默认5s
        readTimeout: 4000
  # 配置 GZIP 来压缩数据
  compression:
    request:
      enabled: true
      # 配置压缩的类型
      mime-types: text/xml,application/xml,application/json
      # 最小压缩值
      min-request-size: 2048
    response:
      enabled: true

#注意：请确保client与server的注册中心和配置中心namespace和group一致
#客户端seata配置,seata的注册中心针对的是TC那边的配置中心、注册中心、服务分组、namespace必须和TC配置成一样，
seata:
  application-id: ${spring.application.name}
  # seata 服务分组，要与服务端配置service.vgroup_mapping的后缀对应
  tx-service-group: default_tx_group
  enable-auto-data-source-proxy: true
  registry:
    # 指定nacos作为注册中心
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace:
      group: SEATA_GROUP

  config:
    # 指定nacos作为配置中心
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: d317c984-c0f3-4fc9-bbae-b64df9d685ca
      group: SEATA_GROUP
      data-id: seataServer.properties      #与nacos配置中心的的data-id一致

      #之前createOrder下单接口一直报错(一两天都没解决)： io.seata.common.exception.FrameworkException: No available service
      #  can not get cluster name in registry config 'service.vgroupMapping.default_tx_group', please make s
      #原因:要在nacos上新建一个命名空间,然后用它自动生成的命名空间id，不要自定义指定命名空间id,造成客户端拉取不到TC配置中心的配置




