#本地选择开启swagger
swagger:
  enabled: true

server:
  #(改)启动端口，一台服务器唯一
  port: 8011
  #(改)应用上下文，统一用/tps-local
  servlet:
    context-path: /jinbiao-cool

spring:
  main:
    allow-bean-definition-overriding: true # 意思是后来发现的bean会覆盖之前相同名称的bean
  application:
    #(改)项目名称，建议使用hsa-tps-local，和包名一致
    name: jinbiao-cool
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/xiaofa_lawyer?connectTimeout=1000000&socketTimeout=3000000&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    database: 0
    timeout: 3000
    #本机redis
#    host: 127.0.0.1 # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password:  # Redis服务器连接密码（默认为空）
#    timeout: 1000ms # 连接超时时间（毫秒）

    #哨兵模式
#    sentinel:
#      master: mymaster #主服务器所在集群名称
#      nodes: 192.168.213.128:26379,192.168.213.128:26380,192.168.213.128:26381

    #集群cluster模式
    password: jinbiao
    cluster:
      nodes:  192.168.213.128:8001,192.168.213.129:8002,192.168.213.130:8003,192.168.213.128:8004,192.168.213.129:8005,192.168.213.130:8006
    lettuce:
      pool:
        max-active: 100           # 默认8
        max-wait: 500ms           # 负值表示没有限制
        max-idle: 80              # 连接池最大空闲连接  默认8
        min-idle: 20              # 连接池最小空闲连接  默认 0

  kafka:
    im-topic-name: IM_T001_DEV
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    listener:
      type: batch               # 批量消费
      concurrency: 1            # 并发数
      poll-timeout: 500         # 轮询消费者时使用的超时（以毫秒为单位）
      ack-mode: manual_immediate   #手动提交offfet 与  enable-auto-commit: true 条件互斥
      retries: 3                # 重试次数
    producer:
      retries: 3                # 重试次数
      batch-size: 16384         # 批量发送的消息数量
      buffer-memory: 33554432   # 32MB的批处理缓冲区
      acks: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: IM_G001_DEV             # 默认消费者组
      auto-offset-reset: earliest       # 最早未被消费的offset
      max-poll-records: 100             # 批量一次最大拉取数据量
      auto-commit-interval: 1000         # 如果'enable.auto.commit'为true，则消费者偏移自动提交给Kafka的频率（以毫秒为单位），默认值为5000。
      enable-auto-commit: false
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

sign:   # 签名的过期时间60s
  maxTime: 180

service:
  version: 1.0.0

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-portal-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: Bearer  #JWT负载中拿到开头

secure:
  ignored:
    urls: #安全路径白名单
    - /thirdPartyService/**
    - /loginVerfy/getShearCaptcha1
    - /caseCenterApi/**
    - /upDownload/**
    - /testPubEvent/**
    - /order/**

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.powersi.entity
  #设置sql打印
  configuration:
    database-id: ${mybatis.database.provider.type:mysql}
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #设置驼峰命名法
    map-underscore-to-camel-case: true

# webSocket启动端口
im:
  server:
    port: 40002                #套接字端口
    allIdleTimeSeconds: 180    #所有类型的空闲超时时间,所有类型的空闲超时时间设定，包括读空闲和写空闲
    readerIdleTimeSeconds: 7   #读空闲超时时间
    writerIdleTimeSeconds: 3   #写空闲超时时间

#showSql
logging:
  level:
    root: info
    com.powersi.dao: debug

#mybatis-plus打印sql信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#Dubbo provider configuration
#dubbo:
#  application:
#    name: dubbo_provider
#  protocol:
#    #(改)连接zookeeper服务地址端口，建议所有的都不一样，且记录下来
#    port: 20880
#    name: dubbo
#    version: 1.0.0
#  registry:
#    #(改)zookeeper服务地址，根据提供修改(zookeeper://IP:端口)
#    protocol: zookeeper
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    #(改)zookeeper服务地址，根据提供修改(zookeeper://IP:端口)
#    address: zookeeper://127.0.0.1:2181
#    #扫描注解包通过该设置将服务注册到zookeeper           dubbo.scan.base-packages=com.wzb.provider.service
#  scan:
#    base-packages: com.powersi.service
#  provider:
#    version: 1.0.0
